
namespace: default
resources:
  - backend.yaml

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: krampoline
  namespace: default
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: frontend-service
              servicePort: 80
              # 여러분의 app path 를 넣어주세요.
              path: /kf757e004c95fa(/|$)(.*)
            pathType: Prefix