
namespace: default
resources:
  - backend.yaml

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: krampoline
  namespace: default
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: backend
              servicePort: 8080
              # 여러분의 app path 를 넣어주세요.
              path: /k6e90852ea92da(/|$)(.*)